services:
  localstack_service:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./localstack:/tmp/localstack

  mailBridge:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    env_file:
      - .env
    depends_on:
      - localstack_service
